[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXTAUTH_URL = "http://localhost:3000"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"
